Swath aggregator CLI
TUW-GEO/ascat pull request #62
Opened 2024-02-16 11:27 UTC by claytharrison

Adds a utility for aggregating collections of swaths by regular time intervals. CLI is accessible via `ascat_temporal_swath_agg`.

Also adds the swath file generator from #61.

2024-02-16 12:17 UTC, sebhahn requested changes
good job!

2024-02-16 12:17 UTC, sebhahn commented on src/ascat/aggregate/aggregators.py
> +            "surface_soil_moisture",
maybe only use surface_soil_moisture and backscatter40 for now

2024-02-16 12:17 UTC, sebhahn commented on src/ascat/aggregate/aggregators.py
> +                f"{out_dir}/ascat_{self.agg}_{chunk_start_str}_{chunk_end_str}.nc",
maybe add spatial sampling and/or product id

2024-02-16 12:17 UTC, sebhahn commented on src/ascat/aggregate/interface.py
> +    parser.add_argument(
this should come from the input filename

2024-02-16 12:17 UTC, sebhahn commented on src/ascat/aggregate/interface.py
> +    parser.add_argument(
or metadata

2024-02-16 14:01 UTC, claytharrison commented
Now it grabs a single swath filename from the filepath, and checks it against the products that we have metadata for using a regex to get the appropriate product id. Possible product ids right now are `H129`, `H129_V1.0`, `H121_V1.0`, `H122`, `SIG0_6.25`, `SIG0_12.5`. To use this on other data, the info will have to be added to `read_native/xarray_io`: both a class that inherits from `SwathIOBase` for reading, as well as an entry to `swath_fname_regex_lookup` so that the ioclass will be findable from a single filename.

2024-02-21 16:25 UTC, claytharrison commented
Everything here should be ready to merge, then I just need to update the changelog

2024-02-22 08:25 UTC, claytharrison commented
Updated the changelog here - all is ready to merge.

2024-02-23 11:17 UTC, sebhahn approved these changes

2024-02-23 11:17 UTC, merged